{
 "title": "Business Metrics",
 "tags": [
  "startpage",
  "home",
  "presentation"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Sign ups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.7)"
    }
   ]
  },
  {
   "title": "Sign outs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_04.counters.requests.count"
    }
   ]
  },
  {
   "title": "Support calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "scale(apps.backend.backend_03.counters.requests.count, 0.3)"
    }
   ]
  },
  {
   "title": "Payments Completed/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(removeAboveValue(scale(statsd.fakesite.counters.session_start.desktop.count, 5), 75), 'Payments')"
    }
   ]
  },
  {
   "title": "Customer Reviews",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(statsd.fakesite.counters.session_start.mobile.count, 'reviews')"
    }
   ]
  },
  {
   "title": "Payments Completed/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'subscribers')"
    }
   ]
  }
 ]
}