{
 "title": "Prometheus - Demo Dashboard",
 "tags": [
  "prometheus",
  "node",
  "misc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_load1{job=\"node\"}, instance)"
    }
   },
   {
    "name": "filesystem_mountpoint",
    "query": {
     "query": "query_result(node_filesystem_size{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"node\", instance=~\"$node:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{job=\"node\", instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu)(node_cpu_seconds_total{job=\"node\", instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "All disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(mode)(irate(node_cpu_seconds_total{job=\"node\", instance=~\"$node:.*\", mode!=\"idle\"}[5m])) > 0",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"node\", instance=~\"$node:.*\"}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", instance=~\"$node:.*\"} - node_memory_MemFree_bytes{job=\"node\", instance=~\"$node:.*\"} - node_memory_Cached_bytes{job=\"node\", instance=~\"$node:.*\"} - node_memory_Buffers_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\", instance=~\"$node:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\", instance=~\"$node:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Filesystem $filesystem_mountpoint usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "filesystem_mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_free_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}